<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <RootNamespace>MiniBrowser</RootNamespace>
    <AssemblyName>MiniBrowser</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="151.3.240" />
  </ItemGroup>
</Project>
